#!/usr/bin/env node
const GraphNode = require('../model/graph-node');

const node2 = new GraphNode(2);
node2.set('data', 'Blake');

const node3 = new GraphNode(3);
node3.set('data', 'Mary');

const node4 = new GraphNode(4);
node4.set('data', 'Jack');

const node1 = new GraphNode(1);
node1.set('data', 'John');
node1.addNeighbors([node2, node3, node4])

process.exit()